apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-ad
  template:
    metadata:
      labels:
        app: db-ad
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ad_service
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: video_sharing_test
          image: postgres
          imagePullPolicy: IfNotPresent
          name: db-ad
          ports:
            - containerPort: 5432