apiVersion: v1
kind: Service
metadata:
  name: db-balance-transaction
spec:
  type: ClusterIP
  ports:
    - name: "db-balance-transaction"
      port: 5432
      targetPort: 5432
  selector:
    app: db-balance-transaction