apiVersion: v1
kind: Service
metadata:
  name: balance-transactions
spec:
  type: ClusterIP
  ports:
    - name: "balance-transactions"
      port: 8085
      targetPort: 8085
  selector:
    app: balance-transactions