apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
        -
          image: mmassolit/gateway
          name: gw
          ports:
            -
              containerPort: 8080