apiVersion: apps/v1
kind: Deployment
metadata:
  name: playbacks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playbacks
  template:
    metadata:
      labels:
        app: playbacks
    spec:
      containers:
        -
          image: mmassolit/playback
          name: playbacks
          ports:
            -
              containerPort: 8087