apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos
  template:
    metadata:
      labels:
        app: videos
    spec:
      containers:
        -
          image: mmassolit/videos
          name: videos
          ports:
            -
              containerPort: 8084